<h1 align="center"><b>Imputation & Missing Values</b></h1>

## **Task 3.1 – Load and Inspect the  Dataset**

### Import Libraries & Load Utility Functions

In [22]:
import sys
import importlib

sys.path.append("../src")

import imputation_utils
importlib.reload(imputation_utils)

from imputation_utils import (
    read_file,
    inspect_data,
    assess_missing_invalid
)

### 1.Loading and  Data Inspection

- Checked dataset shape and columns.
- Reviewed sample rows and data types.
- Checked missing values and duplicates.
- Explored summary statistics.

In [23]:
df = read_file("../data/pew_religion.csv")
inspect_data(df)

1. Dataset Shape:
(36918, 17)

2. Column Names:
['P_SUID', 'WEIGHT', 'YEAR_FROM_CODATE', 'BIRTHDECADE', 'GENDER', 'EDUCREC', 'INC_SDT1', 'RACECMB', 'MARITAL', 'RELTRAD', 'RELIMP', 'ATTNDPERRLS', 'PRAY', 'HAPPY', 'PARTY', 'IDEO', 'AGE_ESTIMATED']

3. First 10 Rows:

c:\Users\admin\Desktop\Ai-Fall\PROG8245-MLP\Week 6\cleaning-imputation-outliers\notebooks\../src\imputation_utils.py:5: DtypeWarning: Columns (16: AGE_ESTIMATED) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,P_SUID,WEIGHT,YEAR_FROM_CODATE,BIRTHDECADE,GENDER,EDUCREC,INC_SDT1,RACECMB,MARITAL,RELTRAD,RELIMP,ATTNDPERRLS,PRAY,HAPPY,PARTY,IDEO,AGE_ESTIMATED
0,10000040.0,4399.707781,2023.0,1990s,A woman,Some college/associate's degree,"$30,000 to less than $40,000",White,Living with a partner,Evangelical Protestant Tradition,Very important,Once a week,Several times a day,Very happy,Republican,Very conservative,28
1,10000060.0,6693.424549,2023.0,1970s,A woman,Master's degree or higher,"$125,000 to less than $150,000",White,Married,Religiously Unaffiliated,Not at all important,Never,Never,Very happy,Democrat,Very liberal,48
2,10000140.0,3080.916226,2024.0,1980s,A woman,College graduate,"$125,000 to less than $150,000",White,Married,Catholic,Very important,Once or twice a month,Once a day,Pretty happy,Independent,Moderate,39
3,10000150.0,5470.685158,2023.0,1960s,A woman,High school or less,DON'T KNOW/REFUSED,White,Married,Religiously Unaffiliated,Not at all important,Never,Never,Not too happy,Republican,Moderate,58
4,10000160.0,2474.921511,2023.0,1970s,A woman,College graduate,"$75,000 to less than $100,000",Black or African-American,Divorced,Historically Black Protestant Tradition,Somewhat important,Seldom,Seldom,Not too happy,Democrat,Liberal,48
5,10000200.0,5220.197875,2024.0,1950s,A woman,Some college/associate's degree,"$30,000 to less than $40,000",Black or African-American,Married,Historically Black Protestant Tradition,Very important,More than once a week,Several times a day,Pretty happy,Democrat,Moderate,69
6,10000240.0,6276.829011,2023.0,1960s,A man,Some college/associate's degree,"$50,000 to less than $75,000",White,Divorced,Evangelical Protestant Tradition,Very important,A few times a year,Seldom,Pretty happy,Independent,Conservative,58
7,10000250.0,7408.343658,2024.0,1980s,A man,College graduate,"$100,000 to less than $125,000",White,Never been married,Religiously Unaffiliated,Not too important,Once or twice a month,Seldom,Not too happy,Independent,Very conservative,39
8,10000280.0,3800.264847,2024.0,1960s,A woman,College graduate,DON'T KNOW/REFUSED,White,Married,Catholic,Somewhat important,Seldom,A few times a week,Very happy,Republican,Moderate,59
9,10000420.0,3901.603222,2023.0,1970s,A woman,College graduate,"$75,000 to less than $100,000",White,Married,Catholic,Not too important,A few times a year,Once a week,Pretty happy,Democrat,Liberal,48

4. Data Types:
P_SUID              float64
WEIGHT              float64
YEAR_FROM_CODATE    float64
BIRTHDECADE             str
GENDER                  str
EDUCREC                 str
INC_SDT1                str
RACECMB                 str
MARITAL                 str
RELTRAD                 str
RELIMP                  str
ATTNDPERRLS             str
PRAY                    str
HAPPY                   str
PARTY                   str
IDEO                    str
AGE_ESTIMATED        object
dtype: object

5. Missing Values:
P_SUID                 1
WEIGHT               370
YEAR_FROM_CODATE       1
BIRTHDECADE            1
GENDER               370
EDUCREC              370
INC_SDT1               1
RACECMB                1
MARITAL                1
RELTRAD                1
RELIMP                 1
ATTNDPERRLS            1
PRAY                   1
HAPPY                370
PARTY                  1
IDEO                   1
AGE_ESTIMATED       6748
dtype: int64

6. Missing Value Percentages:
P_SUID               0.00
WEIGHT               1.00
YEAR_FROM_CODATE     0.00
BIRTHDECADE          0.00
GENDER               1.00
EDUCREC              1.00
INC_SDT1             0.00
RACECMB              0.00
MARITAL              0.00
RELTRAD              0.00
RELIMP               0.00
ATTNDPERRLS          0.00
PRAY                 0.00
HAPPY                1.00
PARTY                0.00
IDEO                 0.00
AGE_ESTIMATED       18.28
dtype: float64

7. Duplicate Rows:
3

8. Summary Statistics:

,P_SUID,WEIGHT,YEAR_FROM_CODATE,BIRTHDECADE,GENDER,EDUCREC,INC_SDT1,RACECMB,MARITAL,RELTRAD,RELIMP,ATTNDPERRLS,PRAY,HAPPY,PARTY,IDEO,AGE_ESTIMATED
count,3.691700e+04,36548.000000,36917.000000,36917,36548,36548,36917,36917,36917,36917,36917,36917,36917,36548,36917,36917,30170
unique,NaN,NaN,NaN,8,5,5,9,6,7,16,5,7,8,4,5,6,25
top,NaN,NaN,NaN,1950s,A woman,Some college/associate's degree,"$150,000 or more",White,Married,Religiously Unaffiliated,Very important,Seldom,Several times a day,Pretty happy,Democrat,Moderate,68
freq,NaN,NaN,NaN,7814,20315,11009,6733,28183,18915,10733,13749,9198,10275,21315,12128,13373,5839
mean,1.108337e+07,6974.734049,2023.136441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,6.217321e+05,7593.243921,0.343261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000004e+07,166.396325,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.054501e+07,2594.530893,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.108171e+07,4614.677544,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.162273e+07,8248.323894,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.215894e+07,84837.102120,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

9. Random Sample Rows:

,P_SUID,WEIGHT,YEAR_FROM_CODATE,BIRTHDECADE,GENDER,EDUCREC,INC_SDT1,RACECMB,MARITAL,RELTRAD,RELIMP,ATTNDPERRLS,PRAY,HAPPY,PARTY,IDEO,AGE_ESTIMATED
14320,10846540.0,22280.802830,2023.0,1990s,In some other way,High school or less,"Less than $30,000",White,Divorced,Religiously Unaffiliated,Not too important,Seldom,Seldom,Very happy,Democrat,Very conservative,28
20546,11206250.0,4884.283179,2023.0,1980s,A man,Some college/associate's degree,"$50,000 to less than $75,000",White,Separated,Evangelical Protestant Tradition,Very important,A few times a year,Once a day,Pretty happy,Republican,Conservative,38
25162,11474560.0,1595.480763,2023.0,1940s or earlier,A man,Some college/associate's degree,"$30,000 to less than $40,000",White,Divorced,Evangelical Protestant Tradition,Very important,Once or twice a month,Several times a day,Very happy,Democrat,Conservative,NaN
18791,11100680.0,26962.588630,2023.0,No answer,DON'T KNOW/REFUSED,NaN,DON'T KNOW/REFUSED,DON'T KNOW/REFUSED,Never been married,Evangelical Protestant Tradition,Very important,Once a week,Once a day,Pretty happy,Something else,DON'T KNOW/REFUSED,NaN
23448,11375340.0,504.963037,2023.0,1950s,A woman,Some college/associate's degree,"Less than $30,000",White,Never been married,Catholic,Very important,Seldom,Several times a day,Very happy,Democrat,Moderate,68

Empty rows: 1

## **Task 3.2 – Assess Missing and Invalid Values**

## Task 2: Missing and Invalid Values

- Checked missing values and their percentages.
- Counted valid observations using `notnull()`.
- Checked `WEIGHT`, `YEAR_FROM_CODATE`, and `AGE_ESTIMATED` for invalid numeric values.
- Converted selected columns to numeric data types.

In [25]:
numeric_cols = ["WEIGHT", "YEAR_FROM_CODATE", "AGE_ESTIMATED"]

df = assess_missing_invalid(df, numeric_cols)

1. Missing Values:
P_SUID                 1
WEIGHT               370
YEAR_FROM_CODATE       1
BIRTHDECADE            1
GENDER               370
EDUCREC              370
INC_SDT1               1
RACECMB                1
MARITAL                1
RELTRAD                1
RELIMP                 1
ATTNDPERRLS            1
PRAY                   1
HAPPY                370
PARTY                  1
IDEO                   1
AGE_ESTIMATED       6748
dtype: int64

2. Missing Value Percentages:
P_SUID               0.00
WEIGHT               1.00
YEAR_FROM_CODATE     0.00
BIRTHDECADE          0.00
GENDER               1.00
EDUCREC              1.00
INC_SDT1             0.00
RACECMB              0.00
MARITAL              0.00
RELTRAD              0.00
RELIMP               0.00
ATTNDPERRLS          0.00
PRAY                 0.00
HAPPY                1.00
PARTY                0.00
IDEO                 0.00
AGE_ESTIMATED       18.28
dtype: float64

3. Valid Observations:
P_SUID              36917
WEIGHT              36548
YEAR_FROM_CODATE    36917
BIRTHDECADE         36917
GENDER              36548
EDUCREC             36548
INC_SDT1            36917
RACECMB             36917
MARITAL             36917
RELTRAD             36917
RELIMP              36917
ATTNDPERRLS         36917
PRAY                36917
HAPPY               36548
PARTY               36917
IDEO                36917
AGE_ESTIMATED       30170
dtype: int64

4. Invalid Numeric Values:
WEIGHT: 0 invalid values
YEAR_FROM_CODATE: 0 invalid values
AGE_ESTIMATED: 1 invalid values
Invalid entries: ['unknown']

5. Updated Data Types:
P_SUID              float64
WEIGHT              float64
YEAR_FROM_CODATE    float64
BIRTHDECADE             str
GENDER                  str
EDUCREC                 str
INC_SDT1                str
RACECMB                 str
MARITAL                 str
RELTRAD                 str
RELIMP                  str
ATTNDPERRLS             str
PRAY                    str
HAPPY                   str
PARTY                   str
IDEO                    str
AGE_ESTIMATED       float64
dtype: object

## **Task 3.3 – Check Duplicates**